### ISSUE TITLE
TODO: Clean up function and extract out the functionality into clean functions that change the buttonStyle

### ISSUE THREAD

**Issue by WSINTRA** [WSINTRA/Savour_v1#19]
TODO: Clean up this function and extract out the functionality into clean functions that change the buttonStyle
Line 130 in App.js

When ChangeText is called there is a setState that changes the button color to light up orange once all form details have been filled out. 
This code is very messy and needs to be broken up into functions that perform one task.

Take a look and try to figure out how you would go about decoupling this section

**Comment by WSINTRA** [comment]
Before looking at the fix, take 30 minutes to study the master branch and see how you would go about solving this problem, then checkout -b YourFix and see if you can solve it, 
If you get stuck have a look at PR #21 and see one way that the problem was solved.

**Comment by speckworks** [comment]
oof. That looks like code spaghetti.  I still don't understand namespaces.  Sorry I'm moving so slow, mate.  I can't keep up with you.

**Comment by WSINTRA** [comment]
Haha it is spaghetti, thats why we need to come up with a nicer solution...
Have a try see if you can untangle it and make an improvement

**Comment by WSINTRA** [comment]
https://github.com/WSINTRA/Savour_v1/pull/21/commits/0bef40dd5e7360a4ef8906b6273d8be3a70516f2
